version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
permissions:
   - object: /
     pattern: "**"
     owner: root
     group: root
hooks:
  Install:
    - location: script/install_npm.sh
      timeout: 15000
      runas: root
  ApplicationStart:
    - location: /home/ec2-user/start.sh
      timeout: 15000
      runas: root
