version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
permissions:
   - object: /
     pattern: "**"
     owner: ec2-user
     group: ec2-user
hooks:
  Install:
    - location: script/install_npm.sh
      timeout: 15000
      runas: ec2-user
  ApplicationStart:
    - location: script/start_server.sh
      timeout: 15000
      runas: ec2-user
