version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
permissions:
   - object: /
     pattern: "**"
     owner: root
     group: root
hooks:
  Install:
    - location: script/install_npm
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/start_server
      timeout: 300
      runas: root
